config/routes.rb
Rails.application.routes.draw do
    root to: 'artists#index'

    resources :artists do
      resources :songs
    end

    namespace :api do
      resources :artists do
        resources :songs
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
    belongs_to :artist, optional: true

    validates :name, presence: true
    validates :name, uniqueness: true
end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController
skip_before_action  :verify_authenticity_token
  def index
    render status: 200, json: {
      artists: Artist.all
    }.to_json
  end

  def show
    artist = Artist.find(params[:id])

    render status: 200, json: {
      artist: artist
    }.to_json
  end
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
skip_before_action  :verify_authenticity_token
  def index
    @songs = artist.songs
    render status: 200, json: {
      songs: Song.all
    }.to_json
  end

  def show
    song =  Song.find(params[:id])

    render status: 200, json: {
      song: song
    }.to_json
  end

  def create
    song = Song.new(song_params)

    if song.save
      render status: 201, json: {
        message: "Song added",
        song: song
      }.to_json
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def update
    song = Song.find(params[:id])
    if song.update(song_params)
        render status: 200, json: {
        message: "Song updated",
        song: song
      }.to_json
    else
       render status: 422, json: {
        message: "Something went wrong! The song is not updated",
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    song = @artist.songs.find(params[:id])
    song.destroy

    render status: 200, json: {
      message: "Song removed"
    }.to_json
  end

  # def remove_all_songs
  #   @artist = Artist.find(params[:artist_id])
  #   @songs = @artist.songs
  #   @songs.destroy_all
  #   respond_to do |format|
  #     format.html { redirect_to artist_path(@artist), notice: 'Songs removed.' }
  #     format.json { render status: 200, location: @artist }
  #   end
  # end

  private

  def song_params
    params.require(:song).permit(:name, :artist_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    def show
      @artist = Artist.find(params[:id])
      @songs = @artist.songs.build
    end

    def index
      @artists = Artist.all
      @song = Song.new

    end

    def new
      @artist = Artist.new
    end

    def create
      @artist = Artist.new(artist_params)
        if @artist.save
          image_params.each do |image|
          @artist.photos.create(image: image)
        end

          redirect_to @artist
        else
          render 'new'
      end
    end

    def destroy
      @artist = Artist.find(params[:id])
      @artist.destroy
      redirect_to root_path, notice: "Artist deleted"
    end


  private


    def image_params
      params[:images].present? ? params.require(:images) : []
    end

    def artist_params
        params.require(:artist).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to artist_path(params[:artist_id]), notice: "Song Deleted!"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

    def index
        @songs = Song.all
        @song = Song.new
        
    end

    def new
        @song = Song.new

    end

    # def create
    #     @song = Song.new(song_params)
    #     @song.artist_id = params[:artist_id]
    #
    #     if @song.save
    #         redirect_to artist_path(params[:artist_id]), notice: "Song Saved!"
    #     else
    #         render 'new'
    #     end
    # end

    def create
      @song = Song.new(song_params.merge(artist_id: params[:artist_id]))

    respond_to do |format|
      if @song.save
        format.html { redirect_to artist_path(@song.artist), notice: "Song Saved!" }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new}
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

    def destroy
        @song = Song.find(params[:id])
        @song.destroy

        respond_to do |format|
          format.html { redirect_to artist_path(params[:artist_id]), notice: "Song removed"}
          format.json { head :no_content }
        end
        # redirect_to artist_path(params[:artist_id]), notice: "Song Deleted!"
    end

    private

    def song_params
        params.require(:song).permit(:name, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
    <% @artist.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>

    <label>Name of the song</label>
    <%= f.text_field :name, placeholder: "Name of the artist", class: "form-control" %>

<hr>
    <label>Photo</label>

    <div class="form-group">
      <span class="btn btn-default">
        Add a Photo for this Artist
        <%= file_field_tag "images[]", type: :file, multiple: false %>
      </span>
    </div>
<hr>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/artists/_show.html.erb
<h1><%=  @artist.artist_name %></h1>

<p>Songs:</p><ul>
    <li><% @songs.each do |song| %>
        <%= song.song_name %>
    <% end %></li>
</ul>

app/views/artists/index.html.erb
<h1>Artists</h1>
<hr>

<% @artists.each do |artist| %>
  <p> <%= link_to artist.name, artist_path(artist.id), class: "btn btn-default" %> </p>
   <hr>
<% end %>
<%= link_to "Add Artist", new_artist_path, class: "btn btn-primary" %>

app/views/artists/new.html.erb
<h1>Add an Artist</h1>

<%= render 'form' %>

app/views/artists/show.html.erb
<p class="create">Add a song</p>
<%= render 'songs/form'%>
<hr>


<h1><%= @artist.name %></h1>
  <hr>

  <% @artist.photos.each do |photo| %>
      <%= image_tag photo.image.thumbnail %>
  <% end %>

  <hr>

<h1>Songs</h1>
      <hr />

<% if @artist.songs.any? %>
  <ul id="all-songs">
    <% @artist.songs.each do |song| %>

      <li class="song">
        <p><%= song.name %></p>
        <!-- <p id="<%="#{song.id}"%>" class="btn remove-button">Remove Song</p> -->
        <a href="/artists/<%= @artist.id %>/songs/<%=song.id%>" data-method="delete" rel="nofollow" class="remove-song btn btn-primary">Remove Song</a>
  </li>
  <hr>
    <% end %>
  </ul>
<% else %>
  <p>This artist appears to have no songs.</p>
<% end %>
<hr>
<hr>

<%= link_to "Back to Artists", root_path, class: "btn btn-primary" %>
<%= link_to "Delete this Artist", artist_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
<a href="#" id="remove-songs">Remove all songs</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

      <%= render "shared/navbar" %>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

 <div class="container">
   <%= yield %>
 </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

          <li><%= link_to "Back to Artists", root_path, class: "btn btn-primary" %></li>

      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for [@artist, @artist.songs.new] do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'input' %>
  
  <!-- <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div> -->
<% end %>

app/views/songs/index.html.erb
<h1>Songs</h1>
<hr>

<% @songs.each do |song| %>
    <p> <%= link_to song.name, artist_songs_path(song.id) %></p>
    <hr>
<% end %>
<%= link_to "Add Song", new_artist_song_path, class: "btn btn-primary" %>

app/views/songs/new.html.erb
<h1>Add a Song</h1>
<hr>
<%= render 'form' %>

app/views/songs/new.js.erb
$('#new_artist_song_path').hide().after("<%= j render 'form' %>");

app/views/songs/show.html.erb
<h1>hello</h1>
<h1><%=  @artist[:id] %></h1>
<hr>
<p>Songs:</p><ul>
    <li><% @songs.each do |song| %>
        <%= song.name %>
        <hr>
    <% end %></li>
</ul>